/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ingest/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Trace */
        post: operations["import_trace_api_ingest_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push Trace */
        post: operations["push_trace_api_ingest_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runner/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Agent */
        post: operations["run_agent_api_runner_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runner/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Stream */
        post: operations["run_stream_api_runner_run_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runner/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skills */
        get: operations["get_skills_api_runner_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traces */
        get: operations["list_traces_api_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_traces__trace_id__get"];
        put?: never;
        post?: never;
        /** Delete Trace */
        delete: operations["delete_trace_api_traces__trace_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Cases */
        get: operations["list_test_cases_api_test_cases_get"];
        put?: never;
        /** Create Test Case */
        post: operations["create_test_case_api_test_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Case */
        get: operations["get_test_case_api_test_cases__test_case_id__get"];
        /** Update Test Case */
        put: operations["update_test_case_api_test_cases__test_case_id__put"];
        post?: never;
        /** Delete Test Case */
        delete: operations["delete_test_case_api_test_cases__test_case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Runs */
        get: operations["list_eval_runs_api_eval_runs_get"];
        put?: never;
        /** Create Eval Run */
        post: operations["create_eval_run_api_eval_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-runs/{eval_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Run */
        get: operations["get_eval_run_api_eval_runs__eval_run_id__get"];
        put?: never;
        post?: never;
        /** Delete Eval Run */
        delete: operations["delete_eval_run_api_eval_runs__eval_run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Evaluation */
        post: operations["run_evaluation_api_eval_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Judge Result */
        post: operations["judge_result_api_judge_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Judge Process */
        post: operations["judge_process_api_judge_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentName
         * @enum {string}
         */
        AgentName: "opencode" | "codex" | "claude-code" | "pi";
        /** Assertion */
        Assertion: {
            /** Code */
            code: string;
            /** Label */
            label?: string | null;
        };
        /** EvalRequest */
        EvalRequest: {
            /** Test Case Id */
            test_case_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /** EvalRunCreate */
        EvalRunCreate: {
            /** Test Case Id */
            test_case_id: string;
            /** Trace Id */
            trace_id: string;
            /**
             * Rule
             * @enum {string}
             */
            rule: "strict" | "unordered" | "subset" | "superset" | "llm-result" | "llm-process";
            /**
             * Result
             * @enum {string}
             */
            result: "passed" | "failed" | "review" | "error";
            /** Score */
            score?: number | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** EvalRunListOut */
        EvalRunListOut: {
            /** Items */
            items: components["schemas"]["EvalRunViewOut"][];
            /** Total */
            total: number;
        };
        /** EvalRunViewOut */
        EvalRunViewOut: {
            /** Id */
            id: string;
            /** Test Case Id */
            test_case_id: string;
            /** Trace Id */
            trace_id: string;
            /** Rule */
            rule: string;
            /** Result */
            result: string;
            /** Score */
            score: number | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExpectedPath
         * @description Expected tool-call path for rule evaluation (tool names in order).
         */
        ExpectedPath: {
            /** Tools */
            tools?: string[];
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Agent */
            agent: string;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            } | unknown[] | null;
        };
        /** JudgeRequest */
        JudgeRequest: {
            /** Trace Id */
            trace_id: string;
        };
        /** LlmUsage */
        LlmUsage: {
            /** Model */
            model?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /**
         * Node
         * @description A recursive observable event node (OTel-span-like).
         */
        "Node-Input": {
            /** Id */
            id: string;
            /** Parent Id */
            parent_id?: string | null;
            type: components["schemas"]["NodeType"];
            /** Name */
            name: string;
            /** Summary */
            summary?: string | null;
            /** @default completed */
            status: components["schemas"]["NodeStatus"];
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Input */
            input?: unknown;
            /** Output */
            output?: unknown;
            tool?: components["schemas"]["ToolCall"] | null;
            llm?: components["schemas"]["LlmUsage"] | null;
            error?: components["schemas"]["TraceError"] | null;
            /** Children */
            children?: components["schemas"]["Node-Input"][];
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * Node
         * @description A recursive observable event node (OTel-span-like).
         */
        "Node-Output": {
            /** Id */
            id: string;
            /** Parent Id */
            parent_id?: string | null;
            type: components["schemas"]["NodeType"];
            /** Name */
            name: string;
            /** Summary */
            summary?: string | null;
            /** @default completed */
            status: components["schemas"]["NodeStatus"];
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Input */
            input?: unknown;
            /** Output */
            output?: unknown;
            tool?: components["schemas"]["ToolCall"] | null;
            llm?: components["schemas"]["LlmUsage"] | null;
            error?: components["schemas"]["TraceError"] | null;
            /** Children */
            children?: components["schemas"]["Node-Output"][];
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "completed" | "running" | "error" | "skipped";
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "skill_start" | "skill_end" | "agent_step" | "tool_call" | "llm_call" | "sub_agent" | "message" | "error" | "custom";
        /** RunRequest */
        RunRequest: {
            /** Agent */
            agent: string;
            /** Task */
            task: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "completed" | "running" | "error" | "cancelled";
        /** StreamRunRequest */
        StreamRunRequest: {
            /**
             * Agent
             * @default opencode
             */
            agent: string;
            /** Task */
            task: string;
            /** Skill Name */
            skill_name?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Cwd */
            cwd?: string | null;
            /**
             * Auto
             * @default true
             */
            auto: boolean;
            /**
             * Timeout
             * @default 300
             */
            timeout: number;
            /** Agent Name */
            agent_name?: string | null;
            /** Model */
            model?: string | null;
        };
        /** TestCaseCreate */
        TestCaseCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Agent */
            agent: string;
            /**
             * Rule
             * @enum {string}
             */
            rule: "strict" | "unordered" | "subset" | "superset" | "llm-result" | "llm-process";
            /** Input Context */
            input_context?: {
                [key: string]: unknown;
            } | null;
            expected?: components["schemas"]["ExpectedPath"];
            /** Assertions */
            assertions?: components["schemas"]["Assertion"][];
        };
        /** TestCaseListOut */
        TestCaseListOut: {
            /** Items */
            items: components["schemas"]["TestCaseViewOut"][];
            /** Total */
            total: number;
        };
        /** TestCaseUpdate */
        TestCaseUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Agent */
            agent?: string | null;
            /** Rule */
            rule?: ("strict" | "unordered" | "subset" | "superset" | "llm-result" | "llm-process") | null;
            /** Input Context */
            input_context?: {
                [key: string]: unknown;
            } | null;
            expected?: components["schemas"]["ExpectedPath"] | null;
            /** Assertions */
            assertions?: components["schemas"]["Assertion"][] | null;
        };
        /** TestCaseViewOut */
        TestCaseViewOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Agent */
            agent: string;
            /** Rule */
            rule: string;
            /** Input Context */
            input_context: {
                [key: string]: unknown;
            } | null;
            expected: components["schemas"]["ExpectedPath"];
            /** Assertions */
            assertions: components["schemas"]["Assertion"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ToolCall */
        ToolCall: {
            /** Name */
            name: string;
            /** Args */
            args?: unknown;
            /** Result */
            result?: unknown;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Trace */
        "Trace-Input": {
            /** Id */
            id: string;
            agent: components["schemas"]["AgentName"];
            /** Tool Version */
            tool_version?: string | null;
            /** Skill Name */
            skill_name?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** @default completed */
            status: components["schemas"]["RunState"];
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            usage?: components["schemas"]["Usage"] | null;
            error?: components["schemas"]["TraceError"] | null;
            root: components["schemas"]["Node-Input"];
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /** Trace */
        "Trace-Output": {
            /** Id */
            id: string;
            agent: components["schemas"]["AgentName"];
            /** Tool Version */
            tool_version?: string | null;
            /** Skill Name */
            skill_name?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** @default completed */
            status: components["schemas"]["RunState"];
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            usage?: components["schemas"]["Usage"] | null;
            error?: components["schemas"]["TraceError"] | null;
            root: components["schemas"]["Node-Output"];
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /** TraceError */
        TraceError: {
            /** Message */
            message: string;
            /** Kind */
            kind?: string | null;
            /** Trace */
            trace?: string | null;
        };
        /** TraceListOut */
        TraceListOut: {
            /** Items */
            items: components["schemas"]["TraceSummaryOut"][];
            /** Total */
            total: number;
        };
        /** TraceSummaryOut */
        TraceSummaryOut: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Skill Name */
            skill_name: string | null;
            /** Session Id */
            session_id: string | null;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Usage */
        Usage: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Models */
            models?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    import_trace_api_ingest_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_trace_api_ingest_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Trace-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_api_runner_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_api_runner_run_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skills_api_runner_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_traces_api_traces_get: {
        parameters: {
            query?: {
                agent?: string | null;
                skill_name?: string | null;
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trace_api_traces__trace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_cases_api_test_cases_get: {
        parameters: {
            query?: {
                agent?: string | null;
                rule?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_case_api_test_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_case_api_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_case_api_test_cases__test_case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_case_api_test_cases__test_case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_runs_api_eval_runs_get: {
        parameters: {
            query?: {
                trace_id?: string | null;
                test_case_id?: string | null;
                result?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_eval_run_api_eval_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_run_api_eval_runs__eval_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_eval_run_api_eval_runs__eval_run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evaluation_api_eval_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_result_api_judge_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_process_api_judge_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
